Fix implicit ints and implicit function declarations (C99 compat)
n2ygk/aprsdigi pull request #11
Opened 2023-02-08 13:06 UTC by fweimer-rh

Include <arpa/inet.h> for inet_addr and inet_ntop.  Include <netax25/axlib.h> for ax25_aton_entry.  To avoid header conflicts, it is necessary to include <netax25/ax25.h> instead of <linux/ax25.h>, too.

This changes avoid build failures with future compilers.

Related to:

* https://fedoraproject.org/wiki/Changes/PortingToModernC
* https://fedoraproject.org/wiki/Toolchain/PortingToModernC

2023-02-08 14:41 UTC, n2ygk requested changes

2023-02-08 14:41 UTC, n2ygk commented on aprsdigi.c
> +#include <netax25/ax25.h>
Are these changes consistent across all flavors of linux?

These are not related to the stated purpose of this MR

2023-02-08 14:47 UTC, fweimer-rh commented on aprsdigi.c
> +#include <netax25/ax25.h>
`<linux/ax25.h>` and `<netax25/axlib.h>` are not compatible (cannot be included at the same time). But we need `<netax25/axlib.h>` for the prototypes.

Sometimes kernel UAPI headers have more recent (more complete) definitions than the userspace library headers (probably most commonly seen with glibc). But for aprsdigi's purposes, libax25 1.1.1 in Fedora is good enough.

2023-02-08 16:26 UTC, n2ygk commented on aprsdigi.c
> +#include <netax25/ax25.h>
@fweimer-rh  Maybe this should be handled in https://github.com/n2ygk/aprsdigi/blob/master/configure.ac then?

2023-02-08 16:36 UTC, fweimer-rh commented on aprsdigi.c
> +#include <netax25/ax25.h>
But is it really necessary? What's the oldest distribution version you are targeting? I just checked, and Debian bullseye does not need this.

If we can't find a distribution that needs this, we can't really test it, can we?

2024-04-09 12:58 UTC, n2ygk commented on aprsdigi.c
> +#include <netax25/ax25.h>
I guess I'll go ahead and accept this and we'll see if it breaks anywhere.

2024-04-09 12:59 UTC, n2ygk approved these changes
Thanks for this. Better late than never. Related to #12.

2024-04-09 12:59 UTC, merged