Limit wide n n
n2ygk/aprsdigi pull request #8
Opened 2020-08-29 22:30 UTC by jsjgruber

Packets specifying digipaths with many hops produce exponentially increasing traffic that can interfere with both normal operation of APRS, not to mention emergency operations.

In situations where it is desirable, this change adds an option -W to limit the SSID being acted on in flooding aliases such as WIDE5-5. With the option -W 3 a received WIDE5-5 will be regarded as WIDE5-3 before processing. Other digipeating solutions might perform a similar (though not identical) function by defining WIDE5-5 as an alias configured for a simple single digipeat (transmitted as WIDE5-5*).

The default is not to enforce any limit.

2020-08-30 19:58 UTC, n2ygk approved these changes
Also nice, just like #7.
Thanks

2020-08-30 19:59 UTC, n2ygk requested changes
Woops. The prior merges means this one needs to be rebased. Please do so @jsjgruber.

2020-08-30 20:02 UTC, jsjgruber commented
Will do.

73

N8MSU

On Sun, Aug 30, 2020, 3:59 PM Alan Crosswell <notifications@github.com>
wrote:

> *@n2ygk* requested changes on this pull request.
>
> Woops. The prior merges means this one needs to be rebased. Please do so
> @jsjgruber <https://github.com/jsjgruber>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/n2ygk/aprsdigi/pull/8#pullrequestreview-478230121>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGFCHJZZLE2K3BQYZJNO5L3SDKVTBANCNFSM4QPHUS6A>
> .
>

2020-08-31 20:07 UTC, jsjgruber commented
@n2ygk Here's hoping I did this right. I haven't done much with github.

Please let me know if I messed up or if you need anything else. Thanks.

BTW, we're running this at K8TIH.

2020-09-01 00:31 UTC, n2ygk approved these changes
LGTM

2020-09-01 00:32 UTC, n2ygk commented
Thanks again and happy to see this code being used by someone other than my club;-)

2020-09-01 00:32 UTC, merged